CodeStrong2023/DevGroup_TercerSem_2024

Java/Leccion01/ar/com/system2023/mundopc/mundopc.java
Carga de actividades asignadas
=> Matias ikaczijk

Python/Leccion01/test_figura_geometrica.py
=> Terminacion videos 4,5,6 Python clase 1

Javascript/Leccion01/01-03-ciclos.js
Agrego carpeta Javascript con la carpeta de la clase 1 y el archivo sobre ciclos.
=> Carpeta javascript clase 1 - ciclos

Javascript/Leccion02/02-03-arreglos.js
=> Leccion 2 de JavaScript

Java/Leccion03/AutoboxingUnboxing/test/TestAutoboxingUnboxing.java, Java/Leccion03/ModificadoresAcceso/paquete1/Clase1.java, Java/Leccion03/ModificadoresAcceso/test/TestModificadoresAcceso.java
Agregar carpeta ModificadoresAcceso y modificar archivo AutoxingUnboxing en la Leccion03 de Java.
=> agregar modificadoresAcceso, modificar AutoboxingUnboxing

Java/Leccion03/ModificadoresAcceso/paquete1/Clase1.java, Java/Leccion03/ModificadoresAcceso/paquete1/Clase2.java, Java/Leccion03/ModificadoresAcceso/paquete1/ClaseHija2.java, Java/Leccion03/ModificadoresAcceso/paquete1/TestDefault.java, Java/Leccion03/ModificadoresAcceso/paquete2/Clase3.java, Java/Leccion03/ModificadoresAcceso/paquete2/Clase4.java, Java/Leccion03/ModificadoresAcceso/test/TestModificadoresAcceso.java
Santi ya esta listo para revisar
=> Agrego video 7-10

Python/Leccion11/Producto.py, Python/Leccion11/test_ordenes.py, Python/Leccion12/Persona.py, Python/Leccion12/Sobrecarga_Operadores.py
Bruno ya esta listo para revisar
=> Clase 3 parte 8 Python, agrego contenido de videos 5-9

Python/Leccion14/mundo_pc/computadora.py, Python/Leccion14/mundo_pc/orden.py, Python/Leccion14/mundo_pc/test_mundo_pc.py
terminacion de los videos del 7 al 9 clase 4 POO de Python
=> terminamos clase 4 POO de python

practicas/codigo.js, practicas/piedrapapeltijeras.html
Agregar modificaciones de prácticas de la clase Programación III día: 15/05/2024
=> Prácticas: Agregar función reiniciar

Python/Excepciones/Leccion01/NumerosIgualesException.py, Python/Excepciones/Leccion01/manejo_excepciones.py
Alejandro ya esta listo para revisar!!
=> Agrego codigo faltante Clase 5 Python

Javascript/Lección04/01-04-objetos.js
Agregar contenido de los videos 7 y 8 de la clase 5 de javascript.
Además corregí el orden del documento.
=> Javascript clase 5: Videos 7 y 8

practicas/avatar/public/avatar.html, practicas/avatar/public/js/avatar.js
Agrego función selección al azar de personaje.
=> Agregar seleccion al azar: Prácticas 29/05

Python/Archivos/Leccion02/leer_archivo.py, Python/Archivos/Leccion02/manejo_archivos.py, Python/Archivos/Leccion02/prueba.txt
Agregar videos 4,5 y 6 de la clase 6 de python
=> Python clase 6: videos 4,5 y 6

Javascript/Leccion05/05-03-clases.js, Javascript/Leccion05/index.html
Terminacion videos 1 y 2 , Clase 7 de JS
=> Terminamos Clase 7 JS video 1 y 2

Javascript/Leccion05/05-03-clases.js
Videos de la semana terminados
=> terminamos videos del 1 al 3 de JS

Java/Leccion08/ManejoExcepciones1/aritmetica/Aritmetica.java, Java/Leccion08/ManejoExcepciones1/excepciones/OperacionExcepcion.java, Java/Leccion08/ManejoExcepciones1/test/TestExepciones.java
Agrego videos 9 - 11 de la clase 8 de Java
=> Java - Clase 8: Videos 9 - 11

Javascript/Leccion07/Cliente.js, Javascript/Leccion07/Empleado.js, Javascript/Leccion07/Persona.js
Agregar videos del 1 al 4 de la clase 9 de Javascript
=> Javascript - Clase 9: Videos 1 - 4

Javascript/Leccion07/PruebaPersonas.js, ProyectoPython/hangman.pyw
Videos 5-8 Clase 9 JS
Corrigiendo ultimos errores del proyecto
=> Clase 9 JavaScript / Update ProyectoPython

Python/Leccion07/capa_datos_persona/Persona.py, Python/Leccion07/capa_datos_persona/conexion.py
Subo los videos 1 al 3 de la Clase 10 b de Python
=> Python - Clase 10 b: Videos 1 al 3

practicas/avatar/public/avatar.html, practicas/avatar/public/js/avatar.js
Actualizo la carpeta prácticas con los últimos avances del proyecto Avatar
=> Actualización proyecto Avatar

Java/Leccion12MsQL/Conexion01.sql, Java/Leccion12MsQL/SistemaEstudiantes/.gitignore, Java/Leccion12MsQL/SistemaEstudiantes/.idea/.gitignore, Java/Leccion12MsQL/SistemaEstudiantes/.idea/encodings.xml, Java/Leccion12MsQL/SistemaEstudiantes/.idea/misc.xml, Java/Leccion12MsQL/SistemaEstudiantes/pom.xml, Java/Leccion12MsQL/SistemaEstudiantes/src/main/java/UTN/Main.java, Java/Leccion12MsQL/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java
Terminacion de los videos del 1-7 y finalizacion de la semana 12 de JAVA
=> JAVA SEMANA 12

Python/Leccion07/capa_datos_persona/conexion.py
Subo los videos del 1 al 5 de la clase 11 b de Python.
Aclaración, borré y modifiqué código previo por que así lo hace el profesor.
=> Python - Clase 11 b: Videos 1 al 5

Java/Leccion08/Leccion08.iml, Java/Leccion12MsQL/SistemaEstudiantes/.idea/vcs.xml, Java/Leccion12MsQL/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java, Java/Leccion12MsQL/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java
Subiendo videos 5-9 de la clase 12 parte 2 de JAVA.
=> Joaquinesposito
